# Copyright 2025 GEM Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Agent loop for task-sync style environments.

Ported from verl 0.7.0 to 0.7.1:
  - AgentLoopBase now receives ``dataset_cls`` / ``data_config`` via ``**kwargs``.
  - Uses ``self.apply_chat_template`` from the base class (handles executor dispatch).
  - ``@rollout_trace_op`` wraps ``run`` so traces line up with the other loops.

task-sync envs differ from GEM planning envs in several key ways:
  - File structure: data.py + env.py + prompt.md
  - Database: SQLite file generated by running data.py
  - Env class: Task_Env(db_path, workspace) -- plain Python class, no gem.core.Env
  - Tools and env are combined in one class (env.tools dict)
  - step() returns (reward, info) -- 2-tuple
  - Prompt comes from a separate prompt.md file
  - Evaluation is workspace-file-based (claim_done triggers env.step)
"""
import asyncio
import importlib.util
import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from verl.experimental.agent_loop.agent_loop import AgentLoopBase, AgentLoopMetrics, AgentLoopOutput, register
from verl.experimental.agent_loop.landlock_sandbox import (
    StatefulSandbox,
    acquire_rollout_slot,
    cleanup_env_dir,
    get_tool_executor,
    release_rollout_slot,
    sandbox_startup_gate,
    teardown_env,
    track_env_dir,
)
from verl.experimental.agent_loop.terminal import TerminalError, TerminalExecutor
from verl.utils.profiler import simple_timer
from verl.utils.rollout_trace import rollout_trace_op
from verl.workers.rollout.replica import TokenOutput

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "INFO"))

# Wall-clock budget for the one-shot setup_code (import env.py + construct
# Task_Env + install the tools proxy). This runs while up to
# VERL_SANDBOX_MAX_CONCURRENT_STARTUPS bring-ups race, so it must absorb
# transient CPU/IO contention -- exceeding it drops the rollout to an empty
# trajectory. Heavy envs finish in <10s uncontended; 60s leaves margin under
# concurrency without masking a genuinely hung kernel.
_SANDBOX_SETUP_TIMEOUT = float(os.getenv("VERL_SANDBOX_SETUP_TIMEOUT", "60.0"))


# ============================================================================
# ToolsProxy Source Code - Injected into Programmatic Tool Call Sandbox
# ============================================================================

TOOLS_PROXY_SOURCE = textwrap.dedent(r'''
class _ToolsProxy:
    """Proxy that allows `tools["function_name"](*args, **kwargs)` inside the programmatic tool call sandbox.
    Also supports `tools.function_name(...)` for backward compatibility."""
    def __getitem__(self, name):
        if name not in env.tools:
            raise KeyError(name)
        def _call(*args, **kwargs):
            return env.tools[name](*args, **kwargs)
        return _call
    def __getattr__(self, name):
        if name not in env.tools:
            raise AttributeError(name)
        def _call(*args, **kwargs):
            return env.tools[name](*args, **kwargs)
        return _call
tools = _ToolsProxy()
''').strip()


SYSTEM_PROMPT = (
    "You are a helpful assistant. Use the provided tools to complete the task. "
    "When you have finished the task, call the 'claim_done' tool to submit your result."
)


_ENV_FILES = ["data.py", "env.py", "prompt.md"]


@dataclass
class TaskSyncEnvState:
    """Encapsulates environment state for a task-sync episode."""

    task_env: Any
    task_prompt: str
    workspace: str
    env_dir: str
    db_path: str
    env_file: str
    task_name: str = ""
    max_tool_calls: int = 50
    enable_ptc: bool = True

    sandbox: Optional[Any] = field(default=None, init=False)
    ptc_sandbox: Optional[Any] = field(default=None, init=False)
    terminal_executor: Optional[Any] = field(default=None, init=False)

    current_num_calls: int = field(default=0, init=False)
    is_done: bool = field(default=False, init=False)
    final_reward: float = field(default=0.0, init=False)

    def get_system_prompt(self) -> str:
        return SYSTEM_PROMPT

    def get_tool_schemas(self) -> list[dict[str, Any]]:
        tool_schemas = self.task_env.get_assistant_tools()

        tool_schemas.append({
            "type": "function",
            "function": {
                "name": "execute_python",
                "description": (
                    "Execute Python 3 code in a stateful session. "
                    "os, json, csv, sys are pre-imported. Use print() to return results. "
                    "State (variables, imports) persists across calls. "
                    "Use relative file paths (e.g., 'data.csv')."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "description": "Python 3 code to execute.",
                        }
                    },
                    "required": ["code"],
                },
            },
        })

        if self.enable_ptc:
            tool_schemas.append({
                "type": "function",
                "function": {
                    "name": "programmatic_tool_call",
                    "description": (
                        "Execute Python code that can call env data tools via "
                        "`tools[\"func_name\"](*args, **kwargs)`. "
                        "State persists across calls. Use print() for output. "
                        "Note: `tools[\"...\"]` only accesses env data tools listed above.\n\n"
                        "USE WHEN: loops, conditionals, or chaining multiple tool calls with intermediate "
                        "processing.\n"
                        "DO NOT USE FOR: single tool calls whose results you need in full without further "
                        "processing -- call tools directly instead.\n\n"
                        "Batch processing:\n"
                        "```python\n"
                        "results = []\n"
                        "for region in ['West', 'East', 'Central']:\n"
                        "    data = tools[\"query_sales\"](region)\n"
                        "    total = sum(row['revenue'] for row in data)\n"
                        "    results.append((region, total))\n"
                        "print(max(results, key=lambda x: x[1]))\n"
                        "```\n\n"
                        "Conditional workflow:\n"
                        "```python\n"
                        "info = tools[\"get_info\"](id='A001')\n"
                        "if info['status'] == 'active':\n"
                        "    details = tools[\"get_details\"](id='A001')\n"
                        "    print(details)\n"
                        "else:\n"
                        "    print('Inactive, skipped')\n"
                        "```"
                    ),
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "code": {
                                "type": "string",
                                "description": (
                                    "Python code. Use tools[\"func_name\"](*args, **kwargs) to call env tools."
                                ),
                            }
                        },
                        "required": ["code"],
                    },
                },
            })

        tool_schemas.append({
            "type": "function",
            "function": {
                "name": "terminal",
                "description": "Execute a shell command in the workspace directory.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "command": {
                            "type": "string",
                            "description": (
                                "Shell command to execute (e.g., \"ls -la\", \"grep -c foo data.csv\")."
                            ),
                        }
                    },
                    "required": ["command"],
                },
            },
        })

        tool_schemas.append({
            "type": "function",
            "function": {
                "name": "claim_done",
                "description": (
                    "Call when tasks are complete to submit your final answer. "
                    "You MUST provide the 'action' parameter containing your complete final response."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "action": {
                            "type": "string",
                            "description": "Your final response.",
                        }
                    },
                    "required": ["action"],
                },
            },
        })

        return tool_schemas

    def execute_tool(self, tool_name: str, arguments: dict[str, Any]) -> tuple[str, bool, bool]:
        self.current_num_calls += 1

        if tool_name not in self.task_env.tools:
            available = ", ".join(self.task_env.tools.keys())
            return f"Tool '{tool_name}' not found. Available: {available}", False, False

        try:
            result = self.task_env.tools[tool_name](**arguments)
            observation = json.dumps(result, ensure_ascii=False, default=str)
            return observation, True, False
        except Exception as e:
            return (
                f"Error executing tool '{tool_name}':\n{type(e).__name__}: {str(e)}",
                False,
                True,
            )

    def step(self, action: str) -> tuple[float, dict[str, Any]]:
        return self.task_env.step(action)


class AgentState(Enum):
    PENDING = "pending"
    GENERATING = "generating"
    PROCESSING_TOOL = "processing_tool"
    TERMINATED = "terminated"


class TaskSyncAgentData:
    """Encapsulates all state for a task-sync episode."""

    def __init__(
        self,
        messages: list[dict[str, Any]],
        env: TaskSyncEnvState,
        tool_schemas: list[dict[str, Any]],
        metrics: dict[str, Any],
        request_id: str,
    ):
        self.messages = messages
        self.env = env
        self.tool_schemas = tool_schemas
        self.metrics = metrics
        self.request_id = request_id

        self.prompt_ids: list[int] = []
        self.response_ids: list[int] = []
        self.response_mask: list[int] = []
        self.response_logprobs: list[float] = []

        self.user_turns: int = 0
        self.assistant_turns: int = 0

        self.final_reward: float = 0.0
        self.dense_reward: float = 0.0
        self.done: bool = False
        self.success: bool = False

        self.programmatic_tool_call_count: int = 0
        self.programmatic_tool_call_error_count: int = 0
        self.execute_python_count: int = 0
        self.terminal_count: int = 0
        self.env_tool_count: int = 0
        self.tool_call_parse_error_count: int = 0

        self.current_tool_calls: list[dict[str, Any]] = []


@register("tasksync_agent")
class TaskSyncAgentLoop(AgentLoopBase):
    """Agent loop for task-sync style environments.

    Handles envs with the structure: data.py + env.py + prompt.md
    where Task_Env is a plain Python class with SQLite-backed tools.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        env_cfg = self.config.actor_rollout_ref.env
        self.max_tool_calls = env_cfg.get("max_tool_calls", 50)
        self.ptc_timeout = env_cfg.get("ptc_timeout", 5.0)
        self.data_py_timeout = env_cfg.get("data_py_timeout", 120)

        # ptc_mode controls whether the programmatic_tool_call tool is exposed.
        #   "ptc"     -> every rollout has PTC
        #   "no-ptc"  -> no rollout has PTC
        #   "mixed"   -> trainer assigns per-group: half of groups have PTC, half don't.
        #                Per-sample enable_ptc is passed in via raw_prompt; the value
        #                read here is only used as a fallback.
        self.ptc_mode = env_cfg.get("ptc_mode", "ptc")
        assert self.ptc_mode in ("ptc", "no-ptc", "mixed"), (
            f"ptc_mode must be 'ptc', 'no-ptc', or 'mixed', got '{self.ptc_mode}'"
        )
        self.enable_ptc_default = self.ptc_mode != "no-ptc"

        # tool_call_format selects how the inner of <tool_call>...</tool_call>
        # (and bare top-level blobs) is parsed:
        #   "auto" -- try XML <function=...>, fall back to JSON (default)
        #   "xml"  -- Qwen3-Coder style only
        #   "json" -- Hermes JSON only (Qwen3-8B); malformed -> log + drop
        self.tool_call_format = env_cfg.get("tool_call_format", "auto")
        assert self.tool_call_format in ("auto", "xml", "json"), (
            f"tool_call_format must be 'auto', 'xml', or 'json', got '{self.tool_call_format}'"
        )

        self.reward_type = env_cfg.get("reward_type", "dense")
        assert self.reward_type in ("dense", "binary"), (
            f"reward_type must be 'dense' or 'binary', got '{self.reward_type}'"
        )

        # Per-error penalty subtracted from the final reward at end of rollout.
        # Counts only programmatic_tool_call failures (sandbox-reported, not
        # heuristic). The total penalty is clipped so the final reward stays
        # non-negative. Default 0.0 disables it; opt in via env.ptc_error_penalty.
        self.ptc_error_penalty = float(env_cfg.get("ptc_error_penalty", 0.0))

        self.prompt_length = self.rollout_config.prompt_length
        self.response_length = self.rollout_config.response_length
        self.max_model_len = self.rollout_config.get(
            "max_model_len", self.prompt_length + self.response_length
        )

        logger.info("TaskSyncAgentLoop initialized")

    @rollout_trace_op
    async def run(self, sampling_params: dict[str, Any], **kwargs) -> AgentLoopOutput:
        metrics: dict[str, Any] = {}
        request_id = uuid4().hex

        # Per-sample reward_type override (e.g. from dense_epoch curriculum)
        reward_type = kwargs.pop("reward_type", self.reward_type)
        if isinstance(reward_type, bytes):
            reward_type = reward_type.decode()

        raw_prompt = kwargs.get("raw_prompt", {})
        extra_info = kwargs.get("extra_info", {}) or {}

        if isinstance(raw_prompt, dict) and "task_info" in raw_prompt:
            task_info = raw_prompt["task_info"]
            max_tool_calls = raw_prompt.get("max_tool_calls", self.max_tool_calls)
            enable_ptc = bool(raw_prompt.get("enable_ptc", self.enable_ptc_default))
        elif "task_info" in extra_info:
            task_info = extra_info["task_info"]
            max_tool_calls = extra_info.get("max_tool_calls", self.max_tool_calls)
            enable_ptc = bool(extra_info.get("enable_ptc", self.enable_ptc_default))
        else:
            raise ValueError("task_info not found in raw_prompt or extra_info")

        sandbox = None
        ptc_sandbox = None
        env_dir = None
        env = None
        agent_data: Optional[TaskSyncAgentData] = None
        # Admission gate: bounds how many rollouts hold live envs/sandboxes at
        # once on this worker (see landlock_sandbox.acquire_rollout_slot).
        # Held for the whole episode and released after cleanup, so the kernel
        # population -- not just bring-up -- is capped regardless of
        # env.group_size.
        await acquire_rollout_slot()
        try:
            try:
                env = await self._create_env_from_task_info(task_info, enable_ptc=enable_ptc)
            except Exception as e:
                logger.error(f"Failed to create env for task {task_info.get('task_name', '?')}: {e}")
                metrics["env_creation_error"] = str(e)
                return self._build_early_termination_output(request_id, metrics)

            env_dir = env.env_dir

            # Sandbox bring-up (fork ipykernel + import env.py + Task_Env init)
            # is the per-rollout step most prone to wall-clock blowup under
            # heavy node-level concurrency. Two changes from the naive path:
            #   - sandbox_startup_gate() caps how many bring-ups race at once
            #     across this AgentLoopWorker (env: VERL_SANDBOX_MAX_CONCURRENT_STARTUPS)
            #   - start() / setup_code execution run in the default executor so
            #     other coroutines (generation, RPC) keep making progress while
            #     a kernel is initializing.
            async with sandbox_startup_gate():
                sandbox = StatefulSandbox(workspace_path=env.workspace, timeout=10.0)
                try:
                    await self.loop.run_in_executor(None, sandbox.start)
                except Exception as e:
                    logger.error(f"Sandbox failed to start for task {env.task_name}: {e}")
                    metrics["sandbox_start_error"] = str(e)
                    return self._build_early_termination_output(request_id, metrics)

                if enable_ptc:
                    ptc_sandbox = StatefulSandbox(workspace_path=env.workspace, timeout=10.0)
                    try:
                        await self.loop.run_in_executor(None, ptc_sandbox.start)
                    except Exception as e:
                        logger.error(f"PTC sandbox failed to start for task {env.task_name}: {e}")
                        metrics["ptc_sandbox_start_error"] = str(e)
                        return self._build_early_termination_output(request_id, metrics)

                    setup_result = await self.loop.run_in_executor(
                        None, self._setup_ptc_sandbox_tools, ptc_sandbox, env
                    )
                    if not setup_result.get("success"):
                        error_msg = setup_result.get("error", "Unknown error")
                        logger.error(f"PTC sandbox setup failed: {error_msg}")
                        metrics["ptc_setup_error"] = error_msg
                        return self._build_early_termination_output(request_id, metrics)

            env.sandbox = sandbox
            env.ptc_sandbox = ptc_sandbox
            env.terminal_executor = TerminalExecutor(env.workspace)

            system_prompt = env.get_system_prompt()
            tool_schemas = env.get_tool_schemas()

            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": env.task_prompt},
            ]

            agent_data = TaskSyncAgentData(
                messages=messages,
                env=env,
                tool_schemas=tool_schemas,
                metrics=metrics,
                request_id=request_id,
            )

            state = AgentState.PENDING
            tool_call_count = 0

            while state != AgentState.TERMINATED:
                if state == AgentState.PENDING:
                    state = await self._handle_pending_state(agent_data, sampling_params)
                elif state == AgentState.GENERATING:
                    if len(agent_data.response_mask) >= self.response_length:
                        state = AgentState.TERMINATED
                        continue
                    if tool_call_count >= max_tool_calls:
                        state = AgentState.TERMINATED
                        continue
                    if len(agent_data.prompt_ids) >= self.max_model_len - 1:
                        state = AgentState.TERMINATED
                        continue

                    state = await self._handle_generating_state(agent_data, sampling_params)
                elif state == AgentState.PROCESSING_TOOL:
                    tool_call_count += len(agent_data.current_tool_calls)
                    state = await self._handle_processing_tool_state(agent_data, reward_type=reward_type)
                else:
                    state = AgentState.TERMINATED

        finally:
            try:
                # A pending cancellation aborts this finally block at its FIRST
                # await, so everything that must happen is either done
                # synchronously (sys.path) or already submitted to an executor
                # (the cleanup futures below run regardless of whether the
                # gather is ever awaited) before that point.
                if env_dir:
                    # Undo the sys.path entry added in _create_env_from_task_info;
                    # otherwise dead env_dir entries accumulate forever (one per
                    # rollout) and slow down every subsequent import.
                    try:
                        sys.path.remove(env_dir)
                    except ValueError:
                        pass
                # Break the Task_Env reference cycle synchronously (before the
                # first await below, which a pending cancellation would abort)
                # so its memory -- and the env module namespace its tools pin --
                # is reclaimed by refcounting instead of leaking until a cyclic
                # GC pass. See landlock_sandbox.teardown_env.
                teardown_env(env)
                cleanup_futures = []
                if ptc_sandbox is not None:
                    cleanup_futures.append(self.loop.run_in_executor(None, ptc_sandbox.cleanup))
                if sandbox is not None:
                    cleanup_futures.append(self.loop.run_in_executor(None, sandbox.cleanup))
                if env_dir:
                    # cleanup_env_dir untracks only on successful removal, so a
                    # half-removed dir (e.g. a dying kernel still writing into
                    # its workspace) is retried by the idle sweep.
                    cleanup_futures.append(self.loop.run_in_executor(None, cleanup_env_dir, env_dir))
                if cleanup_futures:
                    await asyncio.gather(*cleanup_futures, return_exceptions=True)
            finally:
                # Also sweeps orphan kernels and env_dirs once the worker goes
                # idle (end of step) -- see release_rollout_slot().
                release_rollout_slot()

        assert agent_data is not None  # for mypy
        return self._build_output(agent_data)

    def _prepare_env_dir(self, source_path: str, task_name: str) -> str:
        """Blocking part of env creation: copy task files and run data.py.

        Runs in an executor thread (see _create_env_from_task_info) -- it must
        not touch Task_Env or any other thread-affine state. Returns the
        populated env_dir; on failure the dir is removed before re-raising.
        """
        env_dir = tempfile.mkdtemp(prefix=f"tasksync_{task_name.replace('/', '_')}_")
        # Track from creation: if the rollout coroutine is cancelled while this
        # function is still running on its executor thread, the return value is
        # dropped and the coroutine never learns this path -- the idle sweep
        # (release_rollout_slot) then removes it via the tracking set.
        track_env_dir(env_dir)
        try:
            for fname in _ENV_FILES:
                src = os.path.join(source_path, fname)
                if os.path.exists(src):
                    shutil.copy2(src, os.path.join(env_dir, fname))

            r = subprocess.run(
                [sys.executable, "data.py", "--db_path", "data.db", "--workspace", "workspace"],
                cwd=env_dir,
                capture_output=True,
                text=True,
                timeout=self.data_py_timeout,
            )
            if r.returncode != 0:
                raise RuntimeError(f"data.py failed for {task_name}:\n{r.stderr}")
        except Exception:
            cleanup_env_dir(env_dir)
            raise
        return env_dir

    async def _create_env_from_task_info(
        self, task_info: dict[str, Any], enable_ptc: bool
    ) -> TaskSyncEnvState:
        source_path = task_info["source_path"]
        task_name = task_info.get("task_name", os.path.basename(source_path))

        # The copy + data.py subprocess is the slow, blocking part. It used to
        # run synchronously on the event loop, which stalled every other
        # rollout on this worker (generation included) for up to
        # data_py_timeout per rollout -- a step-start serial storm that grows
        # linearly with group_size. Offload it to the executor and put it
        # under the startup gate so at most VERL_SANDBOX_MAX_CONCURRENT_STARTUPS
        # data.py builds compete with kernel bring-ups for node CPU/IO.
        async with sandbox_startup_gate():
            env_dir = await self.loop.run_in_executor(
                None, self._prepare_env_dir, source_path, task_name
            )

        # Importing env.py and constructing Task_Env stay on the event-loop
        # thread: Task_Env may hold thread-affine state (e.g. a sqlite3
        # connection with check_same_thread=True) and is later stepped from
        # this thread (see the correctness note in _execute_tool).
        try:
            db_path = os.path.join(env_dir, "data.db")
            workspace = os.path.join(env_dir, "workspace")

            if env_dir not in sys.path:
                sys.path.insert(0, env_dir)
            env_file = os.path.join(env_dir, "env.py")
            spec = importlib.util.spec_from_file_location("_tasksync_env", env_file)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            Task_Env = mod.Task_Env

            task_env = Task_Env(db_path=db_path, workspace=workspace)

            prompt_path = os.path.join(env_dir, "prompt.md")
            with open(prompt_path, encoding="utf-8") as f:
                task_prompt = f.read()

        except Exception:
            cleanup_env_dir(env_dir)
            try:
                sys.path.remove(env_dir)
            except ValueError:
                pass
            raise

        return TaskSyncEnvState(
            task_env=task_env,
            task_prompt=task_prompt,
            workspace=workspace,
            env_dir=env_dir,
            db_path=db_path,
            env_file=env_file,
            task_name=task_name,
            max_tool_calls=self.max_tool_calls,
            enable_ptc=enable_ptc,
        )

    def _setup_ptc_sandbox_tools(self, sandbox: StatefulSandbox, env: TaskSyncEnvState) -> dict:
        setup_code = textwrap.dedent(f"""\
import sys, os, json, csv
import importlib.util as _ilu

# Load Task_Env from env.py
_spec = _ilu.spec_from_file_location('_task_env_mod', {repr(env.env_file)})
_mod = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
env = _mod.Task_Env(db_path={repr(env.db_path)}, workspace={repr(env.workspace)})

{TOOLS_PROXY_SOURCE}

""")
        result, success = sandbox.execute(setup_code, timeout=_SANDBOX_SETUP_TIMEOUT)
        if not success:
            return {"success": False, "error": result}
        return {"success": True, "output": result}

    async def _handle_pending_state(
        self, agent_data: TaskSyncAgentData, sampling_params: dict[str, Any]
    ) -> AgentState:
        prompt_ids = await self.apply_chat_template(
            agent_data.messages,
            tools=agent_data.tool_schemas,
        )
        agent_data.prompt_ids = prompt_ids
        return AgentState.GENERATING

    async def _handle_generating_state(
        self, agent_data: TaskSyncAgentData, sampling_params: dict[str, Any]
    ) -> AgentState:
        with simple_timer("generate_sequences", agent_data.metrics):
            output: TokenOutput = await self.server_manager.generate(
                request_id=agent_data.request_id,
                prompt_ids=agent_data.prompt_ids,
                sampling_params=sampling_params,
                image_data=None,
            )

        if agent_data.metrics.get("num_preempted") is None:
            agent_data.metrics["num_preempted"] = (
                output.num_preempted if output.num_preempted is not None else -1
            )
        else:
            agent_data.metrics["num_preempted"] += (
                output.num_preempted if output.num_preempted is not None else 0
            )

        agent_data.assistant_turns += 1
        agent_data.response_ids = output.token_ids
        agent_data.prompt_ids += agent_data.response_ids
        agent_data.response_mask += [1] * len(agent_data.response_ids)

        if output.log_probs:
            agent_data.response_logprobs += output.log_probs

        response_text = await self.loop.run_in_executor(
            None, lambda: self.tokenizer.decode(agent_data.response_ids, skip_special_tokens=True)
        )

        agent_data.messages.append({"role": "assistant", "content": response_text})

        tool_calls, parse_errors = self._parse_tool_calls(response_text)
        agent_data.current_tool_calls = tool_calls

        if not tool_calls:
            # Strict mode (restored from the pre-2026-05-12 behaviour): any
            # rollout that fails to produce a parseable tool call -- whether
            # because the model emitted plain text or because the format was
            # malformed -- terminates immediately. Since claim_done was never
            # called, agent_data.final_reward stays at 0. parse_errors is
            # still bumped into a metric so the rate is observable.
            if parse_errors:
                agent_data.tool_call_parse_error_count += 1
            return AgentState.TERMINATED

        return AgentState.PROCESSING_TOOL

    async def _handle_processing_tool_state(
        self, agent_data: TaskSyncAgentData, reward_type: str
    ) -> AgentState:
        tool_calls = agent_data.current_tool_calls
        if not tool_calls:
            return AgentState.TERMINATED

        env = agent_data.env
        tool_messages: list[dict[str, Any]] = []
        terminated = False

        for tool_call in tool_calls:
            tool_name = tool_call.get("name", "")
            tool_args = tool_call.get("arguments", {})

            observation, reward, done = await self._execute_tool(
                env, tool_name, tool_args, agent_data, reward_type=reward_type
            )
            tool_messages.append({"role": "tool", "content": observation, "name": tool_name})

            if done:
                agent_data.done = True
                agent_data.final_reward = reward
                terminated = True
                break

        agent_data.messages.extend(tool_messages)

        if terminated:
            return AgentState.TERMINATED

        tool_response_ids = await self.apply_chat_template(tool_messages)

        if len(agent_data.response_mask) + len(tool_response_ids) >= self.response_length:
            return AgentState.TERMINATED

        agent_data.prompt_ids += tool_response_ids
        agent_data.response_mask += [0] * len(tool_response_ids)

        if agent_data.response_logprobs:
            agent_data.response_logprobs += [0.0] * len(tool_response_ids)

        agent_data.user_turns += 1
        return AgentState.GENERATING

    async def _execute_tool(
        self,
        env: TaskSyncEnvState,
        tool_name: str,
        arguments: dict[str, Any],
        agent_data: TaskSyncAgentData,
        reward_type: str,
    ) -> tuple[str, float, bool]:
        # Correctness model for the offloaded branches below: subprocess-backed
        # tool calls (execute_python / programmatic_tool_call / terminal) run on
        # the shared get_tool_executor() pool so they do not block the worker
        # event loop (which would stall every other rollout's generation). This
        # is safe because each sandbox belongs to exactly one rollout and that
        # rollout awaits its tool calls in order -- no sandbox is ever touched
        # by two threads concurrently. Counters and the result handling stay on
        # the event-loop thread (only the .execute() call is offloaded), so no
        # shared agent_data state is mutated off-thread.
        #
        # claim_done (env.step) and the env-tool fallback (env.execute_tool) run
        # the task's Task_Env *in-process*; that object was constructed on the
        # event-loop thread and may hold thread-affine state (e.g. a sqlite3
        # connection with check_same_thread=True). They therefore stay
        # synchronous on the event loop and are NOT offloaded.
        loop = self.loop
        tool_executor = get_tool_executor()

        if tool_name == "tool_call_parse_error":
            # Synthesised by _handle_generating_state when the model emitted a
            # malformed tool call. Surface the parse error back as a tool
            # observation so the model can self-correct on the next turn,
            # instead of terminating with reward 0.
            return arguments.get("_error", "Tool call could not be parsed."), 0.0, False

        if tool_name == "claim_done":
            action = arguments.get("action", "")
            try:
                reward, info = env.step(action)
                raw_reward = float(reward)
                if raw_reward < 0.0 or raw_reward > 1.0:
                    logger.warning(
                        f"task '{env.task_name}' returned out-of-range score {raw_reward}; "
                        f"clamping to [0, 1]"
                    )
                dense_reward = max(0.0, min(raw_reward, 1.0))
                agent_data.dense_reward = dense_reward
                agent_data.success = True
                if reward_type == "binary":
                    reward = 1.0 if dense_reward == 1.0 else 0.0
                else:
                    reward = dense_reward
                observation = json.dumps(info, ensure_ascii=False, default=str)
                return observation, reward, True
            except Exception as e:
                logger.error(f"Error evaluating solution: {e}")
                return f"Evaluation error: {str(e)}", 0.0, True

        if tool_name == "execute_python":
            code = arguments.get("code", "")
            agent_data.execute_python_count += 1
            sandbox = env.sandbox
            if sandbox is None:
                return "Error: Sandbox not initialized", 0.0, False
            result, _ = await loop.run_in_executor(tool_executor, sandbox.execute, code)
            return result, 0.0, False

        if tool_name == "programmatic_tool_call":
            code = arguments.get("code", "")
            agent_data.programmatic_tool_call_count += 1
            ptc_sandbox = env.ptc_sandbox
            if ptc_sandbox is None:
                agent_data.programmatic_tool_call_error_count += 1
                return "Error: PTC sandbox not initialized", 0.0, False
            result, success = await loop.run_in_executor(tool_executor, ptc_sandbox.execute, code)
            if not success:
                agent_data.programmatic_tool_call_error_count += 1
            return result, 0.0, False

        if tool_name == "terminal":
            command = arguments.get("command", "")
            agent_data.terminal_count += 1
            terminal = env.terminal_executor
            if terminal is None:
                return json.dumps({"error": "Terminal not available"}), 0.0, False
            try:
                result = await loop.run_in_executor(tool_executor, terminal.execute, command)
            except TerminalError as e:
                result = f"[Terminal Error] {e}"
            return result, 0.0, False

        agent_data.env_tool_count += 1
        observation, _is_valid, _has_error = env.execute_tool(tool_name, arguments)
        return observation, 0.0, False

    def _parse_tool_calls(self, response: str) -> tuple[list[dict[str, Any]], list[str]]:
        """Parse all tool calls in the response.

        Returns (calls, errors). ``errors`` is non-empty when the response
        *attempted* a tool call (had <tool_call> / <function=> / a JSON object
        with a "name" key) but parsing failed somewhere. Callers can use this
        signal to surface the error back to the model instead of silently
        terminating the rollout with reward 0.
        """
        calls: list[dict[str, Any]] = []
        errors: list[str] = []

        # Ignore anything emitted inside the model's reasoning block. Qwen3
        # thinking models sometimes leak a <tool_call> into <think>...</think>;
        # only the post-reasoning answer should drive tool execution. If a
        # </think> terminator is present, restrict parsing to the text after the
        # final one. Models without a reasoning block (e.g. the Coder instruct
        # variant) have no </think>, so the full response is parsed unchanged.
        think_close = "</think>"
        think_end = response.rfind(think_close)
        if think_end != -1:
            response = response[think_end + len(think_close) :]

        # XML-style: strict format -- requires <tool_call>...</tool_call> wrapper,
        # with a properly closed <function=NAME>...</function> inside.
        open_tag = "<tool_call>"
        close_tag = "</tool_call>"
        if open_tag in response:
            idx = 0
            while True:
                start = response.find(open_tag, idx)
                if start == -1:
                    break
                end = response.find(close_tag, start + len(open_tag))
                if end == -1:
                    msg = "Unclosed <tool_call> wrapper (missing </tool_call>)"
                    logger.warning(msg + "; dropping call")
                    errors.append(msg)
                    break
                inner = response[start + len(open_tag) : end]
                parsed = self._parse_tool_call(inner, errors)
                if parsed is not None:
                    calls.append(parsed)
                idx = end + len(close_tag)
            return calls, errors

        # JSON-style: scan for all top-level {...} blocks containing a "name" field.
        pos = 0
        while pos < len(response):
            start = response.find("{", pos)
            if start == -1:
                break
            end = self._find_balanced_brace(response, start)
            if end == -1:
                if '"name"' in response[start:]:
                    errors.append(
                        "Unbalanced braces in JSON tool call (could not find matching '}')."
                    )
                break
            blob = response[start : end + 1]
            parsed: Optional[dict[str, Any]] = None
            if '"name"' in blob:
                try:
                    tc = json.loads(blob)
                except (json.JSONDecodeError, ValueError) as e:
                    tc = None
                    errors.append(
                        f"JSON tool call failed to parse: {e}. "
                        f"Snippet: {blob[:200].replace(chr(10), ' ')}"
                    )
                if isinstance(tc, dict) and "name" in tc:
                    args = tc.get("arguments", {})
                    if isinstance(args, str):
                        try:
                            args = json.loads(args)
                        except (json.JSONDecodeError, ValueError) as e:
                            errors.append(
                                f"'arguments' for tool '{tc['name']}' was a string but "
                                f"not valid JSON: {e}"
                            )
                            args = {}
                    parsed = {"name": tc["name"], "arguments": args}
                elif isinstance(tc, dict):
                    errors.append("JSON tool call missing required 'name' field.")
            if parsed is not None:
                calls.append(parsed)
                pos = end + 1
            else:
                pos = start + 1
        return calls, errors

    @staticmethod
    def _find_balanced_brace(s: str, start: int) -> int:
        """Return index of `}` that closes `s[start]` (which must be `{`),
        respecting string literals. Returns -1 if unbalanced."""
        depth = 0
        in_str = False
        esc = False
        for j in range(start, len(s)):
            c = s[j]
            if in_str:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == '"':
                    in_str = False
            elif c == '"':
                in_str = True
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return j
        return -1

    def _parse_tool_call(
        self, block: str, errors: list[str]
    ) -> Optional[dict[str, Any]]:
        """Parse a single tool call from the contents of a <tool_call>...</tool_call>
        block. Dispatches on self.tool_call_format. Appends a descriptive message
        to ``errors`` on failure so the caller can surface it to the model."""
        fmt = getattr(self, "tool_call_format", "auto")
        stripped = block.strip()

        if fmt == "json":
            return self._parse_tool_call_json(stripped, errors)
        if fmt == "xml":
            return self._parse_tool_call_xml(block, errors)
        # auto
        if "<function=" in block:
            return self._parse_tool_call_xml(block, errors)
        if stripped.startswith("{"):
            return self._parse_tool_call_json(stripped, errors)
        msg = "Tool call inside <tool_call> has neither <function=...> nor a JSON object."
        logger.warning(msg + " Dropping.")
        errors.append(msg)
        return None

    def _parse_tool_call_json(
        self, blob: str, errors: list[str]
    ) -> Optional[dict[str, Any]]:
        """Parse Hermes-style JSON tool call: {"name": ..., "arguments": {...}}."""
        try:
            obj = json.loads(blob)
        except (json.JSONDecodeError, ValueError) as e:
            preview = blob[:200].replace("\n", "\\n")
            logger.error(f"tool_call_format=json: JSON parse failed ({e}); dropping. raw='{preview}'")
            errors.append(f"JSON parse failed: {e}. Snippet: {preview}")
            return None
        if not isinstance(obj, dict) or "name" not in obj:
            preview = blob[:200].replace("\n", "\\n")
            logger.error(f"tool_call_format=json: missing 'name' field; dropping. raw='{preview}'")
            errors.append("JSON tool call missing required 'name' field.")
            return None
        name = obj["name"]
        if not isinstance(name, str) or not name:
            logger.error(f"tool_call_format=json: invalid 'name' field; dropping. raw='{blob[:200]}'")
            errors.append("JSON tool call 'name' field is empty or not a string.")
            return None
        args = obj.get("arguments", {})
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except (json.JSONDecodeError, ValueError) as e:
                errors.append(
                    f"'arguments' for tool '{name}' was a string but not valid JSON: {e}"
                )
                args = {}
        if not isinstance(args, dict):
            errors.append(
                f"'arguments' for tool '{name}' must be a JSON object, got {type(args).__name__}."
            )
            args = {}
        return {"name": name, "arguments": args}

    def _parse_tool_call_xml(
        self, block: str, errors: list[str]
    ) -> Optional[dict[str, Any]]:
        try:
            func_start = block.find("<function=")
            if func_start == -1:
                msg = "Tool call missing <function=...> tag."
                logger.warning(msg + " Dropping.")
                errors.append(msg)
                return None

            func_part = block[func_start + len("<function=") :]
            name_end = func_part.find(">")
            if name_end == -1:
                msg = "Malformed <function=...> tag (missing '>')."
                logger.warning(msg + " Dropping.")
                errors.append(msg)
                return None
            func_name = func_part[:name_end].strip()
            if not func_name:
                msg = "Empty function name in <function=...> tag."
                logger.warning(msg + " Dropping.")
                errors.append(msg)
                return None

            remaining = func_part[name_end + 1 :]
            close_idx = remaining.find("</function>")
            if close_idx == -1:
                msg = f"Tool call '{func_name}' missing </function> closing tag."
                logger.warning(msg + " Dropping.")
                errors.append(msg)
                return None
            params_block = remaining[:close_idx]

            arguments: dict[str, Any] = {}
            if "<parameter=" in params_block:
                params = params_block.split("<parameter=")
                for param in params[1:]:
                    pname_end = param.find(">")
                    if pname_end == -1:
                        msg = f"Malformed <parameter=...> in '{func_name}' (missing '>')."
                        logger.warning(msg + " Dropping call.")
                        errors.append(msg)
                        return None
                    param_name = param[:pname_end].strip()
                    if not param_name:
                        msg = f"Empty parameter name in '{func_name}'."
                        logger.warning(msg + " Dropping call.")
                        errors.append(msg)
                        return None
                    after = param[pname_end + 1 :]
                    pclose_idx = after.find("</parameter>")
                    if pclose_idx == -1:
                        msg = (
                            f"Parameter '{param_name}' in '{func_name}' missing "
                            f"</parameter> closing tag."
                        )
                        logger.warning(msg + " Dropping call.")
                        errors.append(msg)
                        return None
                    param_value_raw = after[:pclose_idx].strip()
                    arguments[param_name] = self._parse_param_value(param_value_raw)

            return {"name": func_name, "arguments": arguments}
        except Exception as e:
            logger.warning(f"Error parsing tool call: {e}")
            errors.append(f"Unexpected error parsing XML tool call: {e}")
            return None

    def _parse_param_value(self, param_value_raw: str) -> Any:
        if not param_value_raw:
            return param_value_raw

        if param_value_raw.lower() in {"true", "false"}:
            return param_value_raw.lower() == "true"

        try:
            if "." in param_value_raw:
                return float(param_value_raw)
            else:
                return int(param_value_raw)
        except (ValueError, TypeError):
            pass

        try:
            return json.loads(param_value_raw)
        except (json.JSONDecodeError, ValueError):
            pass

        return param_value_raw

    def _build_output(self, agent_data: TaskSyncAgentData) -> AgentLoopOutput:
        response_ids = (
            agent_data.prompt_ids[-len(agent_data.response_mask):] if agent_data.response_mask else []
        )
        prompt_ids = (
            agent_data.prompt_ids[: len(agent_data.prompt_ids) - len(agent_data.response_mask)]
            if agent_data.response_mask
            else agent_data.prompt_ids
        )
        rollout_length = len(prompt_ids) + len(response_ids)

        if len(prompt_ids) > self.prompt_length:
            prompt_ids = prompt_ids[-self.prompt_length :]

        response_ids = response_ids[: self.response_length]
        response_mask = agent_data.response_mask[: self.response_length]
        response_logprobs = (
            agent_data.response_logprobs[: self.response_length]
            if agent_data.response_logprobs
            else None
        )

        is_truncated = (
            len(agent_data.response_mask) >= self.response_length
            or rollout_length >= self.max_model_len
        )

        ptc_error_count = agent_data.programmatic_tool_call_error_count
        ptc_error_penalty = self.ptc_error_penalty * ptc_error_count
        # Clip to >= 0 so the penalty can never make a non-negative reward
        # turn negative (avoids GRPO advantage flips driven purely by errors).
        penalized_reward = max(float(agent_data.final_reward) - ptc_error_penalty, 0.0)

        output = AgentLoopOutput(
            prompt_ids=prompt_ids,
            response_ids=response_ids,
            response_mask=response_mask,
            response_logprobs=response_logprobs,
            multi_modal_data={},
            num_turns=agent_data.user_turns + agent_data.assistant_turns + 1,
            metrics=AgentLoopMetrics(
                generate_sequences=agent_data.metrics.get("generate_sequences", 0.0),
                tool_calls=agent_data.metrics.get("tool_calls", 0.0),
                num_preempted=agent_data.metrics.get("num_preempted", -1),
            ),
            # task-sync computes its reward inside env.step(); surface it here so
            # the agent_loop `_compute_score` path short-circuits and does not
            # invoke the generic reward_loop worker (which expects `data_source`
            # in non_tensor_batch -- task-sync never populates that field).
            reward_score=penalized_reward,
            extra_fields={},
        )

        output.extra_fields["reward_extra_info"] = {
            "episode_reward": penalized_reward,
            "episode_reward_raw": agent_data.final_reward,
            "dense_reward": agent_data.dense_reward,
            "episode_success": agent_data.success,
            "acc": float(agent_data.success),
            "episode_turns": agent_data.assistant_turns,
            "rollout_length": rollout_length,
            "truncated": is_truncated,
            "programmatic_tool_call_count": agent_data.programmatic_tool_call_count,
            "programmatic_tool_call_error_count": ptc_error_count,
            "ptc_error_penalty": ptc_error_penalty,
            "execute_python_count": agent_data.execute_python_count,
            "terminal_count": agent_data.terminal_count,
            "env_tool_count": agent_data.env_tool_count,
            "tool_call_parse_error_count": agent_data.tool_call_parse_error_count,
        }
        output.extra_fields["messages"] = agent_data.messages

        return output

    def _build_early_termination_output(
        self, request_id: str, metrics: dict[str, Any]
    ) -> AgentLoopOutput:
        pad_token_id = self.tokenizer.pad_token_id if self.tokenizer.pad_token_id is not None else 0

        return AgentLoopOutput(
            prompt_ids=[pad_token_id],
            response_ids=[pad_token_id],
            response_mask=[0],
            response_logprobs=[0.0],
            multi_modal_data={},
            num_turns=0,
            metrics=AgentLoopMetrics(),
            # See note in build_output: task-sync must surface reward_score to
            # short-circuit the generic reward_loop worker.
            reward_score=0.0,
            extra_fields={
                "reward_extra_info": {
                    "episode_reward": 0.0,
                    "episode_reward_raw": 0.0,
                    "dense_reward": 0.0,
                    "episode_success": False,
                    "acc": 0.0,
                    "episode_turns": 0,
                    "rollout_length": 0,
                    "truncated": False,
                    "programmatic_tool_call_count": 0,
                    "programmatic_tool_call_error_count": 0,
                    "ptc_error_penalty": 0.0,
                    "execute_python_count": 0,
                    "terminal_count": 0,
                    "env_tool_count": 0,
                    "tool_call_parse_error_count": 0,
                },
                "messages": [],
            },
        )
